spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: iwha
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop

sample:
  value: 123